server:
  port: 8080
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
com:
  star:
    blog:
      cache:
        local-size: 50
        redis-size: 100
        access-time: 1
        write-time: 2
    bloom-filter:
      comment:
        miss-precent: 0.1
      blog:
        miss-precent: 0.1
    retry:
      retry-size: 3
      retry-ttl: 300
    comment:
      page-size: 10
    jwt:
      secret-key: 5f4dcc3b5aa765d61d8327deb882cf99a61c41e383d3a7e92b64819fa0e264
      exp: 3600000
      token-name: authentication
spring:
  application:
    name: HighConcurrent
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/highcurrent
    username: root
    password: 1234
  data:
    redis:
      database: 5
      host: 192.168.220.128
      port: 6379
      timeout: 5000
      password: 123456
  rabbitmq:
    host: 192.168.220.128
    port: 5672
    virtual-host: /
    username: star
    password: 123
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.star.highconcurrent.controller


#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: true
    username: admin
    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 用户模块

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation: DEBUG
